spring.config.import=file:env.properties
spring.application.name=PistakioGelatoBE
server.port=${PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
jwt.secret=${JWT_SECRET}
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.success-url=${STRIPE_SUCCESS_URL}
stripe.cancel-url=${STRIPE_CANCEL_URL}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
